---
resources:
- name: cd_docker_platform_image
  type: image
  versionTemplate:
    sourceName: "nginx" # replace with your fully qualified image URL
    isPull: false
    versionName: "master.10"
- name: cd_docker_platform_cluster
  type: cluster
  integration: "GKE"
  pointer:
    sourceName: "nginx-1-cluster"
    region: "us-central1-a"

jobs:
- name: cd_docker_platform_manifest
  type: manifest
  steps:
  - IN: cd_docker_platform_image

- name: cd_docker_platform_deploy
  type: deploy
  steps:
  - IN: cd_docker_platform_manifest
  - IN: cd_docker_platform_cluster
  - TASK: managed
    deployMethod: replace
