---
resources:
- name: repo_k8s_nginx
  type: gitRepo
  integration: github
  versionTemplate:
    sourceName: kkitai/k8s-nginx
- name: cd_docker_platform_cluster
  type: cluster
  integration: "GKE"
  pointer:
    sourceName: "nginx-1-cluster"
    region: "us-central1-a"

jobs:
- name: cd_docker_platform_deploy
  type: deploy
  method: blueGreen
  steps:
  - IN: repo_k8s_nginx
  - IN: cd_docker_platform_cluster
  - TASK: managed
    deployMethod: replace
